#!/bin/sh

scriptpath=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )

dafny="$scriptpath/../local-dafny/Scripts/dafny"

dafnyVerify="$dafny /timeLimit:20 /compile:0  /noNLarith /autoTriggers:1 /vcsCores:10"

files="$scriptpath/../lib/* $scriptpath/spec/hosts.dfy $scriptpath/spec/distributedSystem.dfy $scriptpath/spec/spec.dfy $scriptpath/proof/messageInvariants.dfy $scriptpath/proof/monotonicityInvariants.dfy $scriptpath/proof/applicationProof.dfy"

echo "Verifying $files" | tr " " "\n"
time $dafnyVerify $files